sudo: required
dist: trusty
services:
  - docker
language: python
python:
  - "2.7"

install:
  - sudo pip install yamllint
  - sudo apt-get update -qq

script:
  - yamllint -c yamlconf $(find . -path './envs' -prune -o -name '*.yml' -print -o -name '*.yaml' -print)
  - gofmt -l .
  - [ $( /usr/local/go/bin/gofmt -l . | grep -v "remoteabac" | wc -l ) -eq 5 ]
  - find . -name "*.sh" | grep -v "\.\/remoteabac\/tests\/run.sh" | xargs -L1 bash -n

notifications:
  email: true
  slack:
    rooms:
      - blue-alchemy:OTG2kwQwHRx8ZieTwB3WsrVD#dove-github
    on_start: never
    on_failure: always
    on_success: change
    on_pull_requests: false
